name: Test Tunnel

on: push

jobs:
  test-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
          uses: 
            with:
              node-version: 12
      - run: npm install

      - name: Start LambdaTest Tunnel
        id: tunnel
        uses: ./ # Uses an action in the root directory
        with:
          user: ${{ secrets.LT_EMAIL }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "test tunnel"

      - name: Run Test Case
        env:
          username: ${{ secrets.LT_USERNAME }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "test tunnel"
          
      - name: Run Test Case Of Smart UI
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install pip install Appium-Python-Client
          python android.py
    

      - name: Export Tunnel Logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: tunnel_logs
          path: ${{ steps.tunnel.outputs.logFileName }}
